[build]
target = ".cargo/x86_64-totobird.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std          = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
